def Menu():
    print("-" * 45)
    print("Escolha uma opção abaixo:")
    print("1 - Cadastrar um novo jogador")
    print("2 - Mostrar jogadores cadastrados")
    print("3 - Mostrar relatorio")
    print("4 - Pesquisar jogador")
    print("5 - Alterar uma informação")
    print("6 - Remover um jogador")
    print("7 - Mostrar estatisticas gerais de todos")
    print("8 - Encerrar programa")
    print("-" * 45)
